language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install --prefer-source

script: ./vendor/bin/phpunit --colors tests

cache:
    directories:
        - vendor

