- shell: uname -m
  ignore_errors: yes
  register: uname_m

- name: Install a list of packages
  apt:
   name: "{{ packages }}"
  vars:
   packages:
   - apt-transport-https
   - ca-certificates
   - curl
   - gnupg-agent
   - software-properties-common

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add nginx apt repositor
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu '{{ uname_m }}' stable"
    state: present

- name: Update repositories
  apt:
   upgrade: yes
   update_cache: yes

- name: Install a list of packages
  apt:
   name: "{{ packages }}"
  vars:
   packages:
   - docker-ce
   - docker-ce-cli
   - containerd.io