- shell: uname -s
  ignore_errors: yes
  register: uname_s

- shell: uname -m
  ignore_errors: yes
  register: uname_m
  
- name: Install docker-compose
  command: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-'{{uname_s.stdout}}'-'{{uname_m.stdout}}'" -o /usr/local/bin/docker-compose
  