name: Build
on: push
jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vars:
        - target: dev
          url: test-dev
        - target: prod
          url: test-prod
    steps:
      - name: my-step
        run: echo "Hello World!"
        with:
          target-step: ${{ matrix.vars.target }}
          url-step: ${{ matrix.vars.url }}