name: Build
on: push
jobs:
  build-image:
    name: build to ${{ matrix.vars.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vars:
          - target: dev
            appurl: test-dev
    steps:
      - name: my-step
        run: |
          echo "${{ matrix.vars.target }} : ${{ matrix.vars.appurl }}"
